### PR TITLE
Update ESX Identity

### PR DESCRIPTION
**Pull request by LazarusOfTheFallen**
- Remove experimental deferral method (for now)
- Remove UseSteamID config option, as editing this for ESX should automatically adjust this by itself
- Attempt fix to Nui getting stuck

### CODE REVIEW

**Comment by Richards0nd** [comment]
SCRIPT ERROR: @esx_identity/server/main.lua:54: attempt to index a nil value (global 'deferrals')
> cb (@es_extended/server/main.lua:216)
> cb (@async/async.lua:28)
> ref (@es_extended/server/main.lua:209)
>  (@mysql-async/mysql-async.js:15897)

**Comment by Moonlgiht111** [comment]
Error parsing script @esx_identity/server/main.lua in resource esx_identity: @esx_identity/server/main.lua:22: unexpected symbol near ')'
Failed to load script server/main.lua.

I get this error

**Comment by LazarusOfTheFallen** [comment]
Ignore this PR, I will recreate it later. It was forgotten when I joined dev work on ESX2.

**Comment by Moonlgiht111** [comment]
> Ignora este PR, lo volveré a recrear más tarde. Se olvidó cuando me uní al trabajo de desarrollo en ESX2.

Thank you very much! I will be careful!

**Pull request closed without merging**
